### ISSUE TITLE
не стартует addon

### ISSUE THREAD

**Issue by rambai** [maxifly/yaBackup#3]
Ошибка такая:
Logger: homeassistant.config_entries
Source: custom_components/yabackup/__init__.py:45
Integration: YandexDiskBackup ([documentation](https://github.com/maxifly/YaBackup), [issues](https://github.com/maxifly/YaBackup/issues))
First occurred: 12:26:26 PM (1 occurrences)
Last logged: 12:26:26 PM

Error setting up entry Backup to YandexDisk for yabackup
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/yabackup/__init__.py", line 45, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by maxifly** [comment]
Знаете, эта интеграция всё равно потребует ручных вмешательств, так как в контейнер homeassistant штатно не смаппирован каталог с бакапами. Придётся постоянно останавливать контейнер и добавлять этот каталог вручную после каждого обновления. Поэтому я решил не развивать эту интеграцию больше.
Я сделал аналогичный по функциональности addon
https://github.com/maxifly/YaBackupAddon

Который штатно запускается в отдельном контейнере и потому имеет доступ к бакапам без ручных вмешательств в систему. 

Извините, что долго не отвечал, просто не отслеживал как тут дела.

**Comment by Andrey-simf** [comment]
У меня та же ошибка, а [YaBackupAddon](https://github.com/maxifly/YaBackupAddon) вообще не хочет устанавливаться, говорит что он не является интеграцией

**Comment by maxifly** [comment]
> У меня та же ошибка, а [YaBackupAddon](https://github.com/maxifly/YaBackupAddon) вообще не хочет устанавливаться, говорит что он не является интеграцией

А можно подробнее,  как именно он говорит, что не является интеграцией, что в логах HA и какой тип установки HA у Вас.

**Comment by Andrey-simf** [comment]
НА Core 2024.10.4
Тип установки Supervised
<img width="970" alt="Снимок экрана 2024-11-06 в 13 26 35" src="https://github.com/user-attachments/assets/e0674d0d-8fea-4afb-9d43-dcd1791022ba">
В логах ошибок не выдает

**Comment by maxifly** [comment]
Вы пытаетесь интеграцию как аддон ставить.
Вот правильный адрес. Он же репозиторий, куда пишите баги, если что. (А этот я чисто для истории оставил - не работает оно так)
https://github.com/maxifly/YaBackupAddon

**Comment by Andrey-simf** [comment]
Спасибо, странно, по-моему ссылку попировал, но видно что то пошло не так ))

Но у меня все равно не работает, не чего не сохраняет на ЯД 

Мои настройки аддона
<img width="1057" alt="Снимок экрана 2024-11-06 в 22 34 52" src="https://github.com/user-attachments/assets/6aa7381e-6188-44da-9211-7ab7d8df7812">

Статус выведенного сенсора 
<img width="524" alt="Снимок экрана 2024-11-06 в 22 36 42" src="https://github.com/user-attachments/assets/fc338815-263e-4f55-8f82-0fc438843573">

И ошибка в журнале еще есть какая то 
<img width="1138" alt="Снимок экрана 2024-11-06 в 22 34 17" src="https://github.com/user-attachments/assets/f7a86405-2738-4c80-89a7-f75245e19fff">


И лог самого аддона 
[ybg.log](https://github.com/user-attachments/files/17652222/ybg.log)
